### ISSUE TITLE
Roles not getting assigned

### ISSUE THREAD

**Issue by jjwedemyer** [warlof/seat-discord-connector#11]
heya,
i've run into the problem that roles are not getting assigned on discord even though the jobs are dispatched. Also on connected discord accounts manually assigned roles are getting removed.

If there's any ideas on how to fix i'd appreciate them.

Regards,
Jakob

**Comment by warlof** [comment]
Hello @jjwedemyer ,

what about jobs status ? Did you see any failed one ?
Can you show me your filters ?

**Comment by zuiji** [comment]
SeAT Super User's dont get roles Discord-Connector 
used sidebar to connect to the server. 

Also Discord server owner dont get roles even as Discord-Connector bot are the first atop of the Role list.

**Comment by warlof** [comment]
@zuiji can you show me your filters as well?

**Comment by geedon** [comment]
Hi, I'm getting a similar issue. with version 3.1.0. The plugin connected OK and successfully removed all the roles but its not assigning them back again. Even the basic corp role doesn't seem to work. Is there some way to debug this?

**Comment by geedon** [comment]
My issue was related to a missing cron tab entry for artisan. I did a bit of a manual docker install of all this and must have missed this step. I Added the following to cron so that the eveseat scheduler actually does something:

* * * * * /usr/local/bin/php {full path to install directory}/eveseat/artisan schedule:run >> /var/log/artisan_cron.log 2>&1
